name: 'Simple Unity CI'
description: 'Build a Unity project with SimpleUnityCI'
inputs:
  url:
    description: 'URL of your build server'
    required: true
  data:
    description: 'Request data JSON'
    required: true
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'

